### ISSUE TITLE
Link to use this form doesn't work on my side

### ISSUE THREAD

**Issue by sebpca** [ebiwd/EBI-Icon-fonts#10]
Need a new icon? link  (introduction text - Need a new icon section) doesn't work on my side... asking for permission

**Comment by khawkins98** [comment]
It looks like the form has been set to only allow submission from EBI Google Apps accounts. I've asked External Relations to open it up. 

In the meantime you can also just ask Spencer by email (spencer [at] ebi.ac.uk).

**Comment by sebpca** [comment]
Thanks.
