### ISSUE TITLE
SVG version of the download icon (at least)

### ISSUE THREAD

**Issue by sebpca** [ebiwd/EBI-Icon-fonts#11]
Hi I would need a stable link to the EBI download icon (SVG format) to replace the default icon used in Highchart where we can use only link to icon and no css-font related. Do you think we can get that  soonish?

Thanks a lot

**Comment by khawkins98** [comment]
These will be part of v1.2 -- good news is that you can download the batch of SVGs and PNGs in the 1.2 dev branch. 

For SVGs, see: https://github.com/ebiwd/EBI-Icon-fonts/tree/v1.2/source

**Comment by khawkins98** [comment]
The 1.2 branch isn't on prod yet, but you can link to dev for the time being: http://wwwdev.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.2/EBI-Functional/static/svg/download.svg

**Comment by sebpca** [comment]
ok thanks for the information. Glad to see that it will be available in the next release.
