### ISSUE TITLE
New file icons

### ISSUE THREAD

**Issue by tschaka1904** [ebiwd/EBI-Icon-fonts#12]
It would be great to have a 'PSI-MI JSON' and a 'PSI-MI ComplexTab' icon.

**Comment by khawkins98** [comment]
Have created a new "PSI-MI JSON" icon. 
![image](https://user-images.githubusercontent.com/928100/36377721-11222948-1570-11e8-9da8-b729ff6051c6.png)


I see there's also already a "tab" icon ![image](https://user-images.githubusercontent.com/928100/36377712-02057cee-1570-11e8-9760-3f0354107c3b.png), not sure if that's distinct from ComplexTab?

**Comment by khawkins98** [comment]
Going to close this one -- if someone wants to make the case for a more verbose ComplexTab icon, just comment and reopen.
