### ISSUE TITLE
font files missing

### ISSUE THREAD

**Issue by mandarsd** [ebiwd/EBI-Icon-fonts#13]
Unable to test the release candidate code because of missing font files (imported in font.css)

**Error FYR :** 
```
./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/EBI-Icon-fonts/fonts.css
Module not found: Error: Can't resolve './EBI-Chemistry/fonts/EBI-Chemistry.eot' in '..\node_modules\EBI-Icon-fonts'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/EBI-Icon-fonts/fonts.css 6:4734-4784 6:4808-4858
 @ ./~/EBI-Icon-fonts/fonts.css
 @ multi ./~/ebi-framework/libraries/foundation-6/css/foundation-lite.min.css ./~/ebi-framework/css/ebi-global.css ./~/EBI-Icon-fonts/fonts.css ./src/md-pdbe-theme.scss ./src/styles.css
```

**Comment by khawkins98** [comment]
Is this when you try to build the EBI-Icon-fonts repo on your local?

**Comment by khawkins98** [comment]
One thought, if you're pulling in the EBI-Icon-fonts repo, make sure you're pulling the `1.2` branch. 

**Do not** pull the `1.2-code` branch unless you plan to build it.

**Comment by khawkins98** [comment]
Ok, I think I can guess what happened -- you must have downloaded the zip from https://github.com/ebiwd/EBI-Icon-fonts/tree/v1.2-rc-1 -- which would be the `1.2-code` branch. I'll have a think about how I can clear up confusion on this. 

For the moment, just use this zip: https://github.com/ebiwd/EBI-Icon-fonts/archive/v1.2.zip

**Comment by mandarsd** [comment]
Yes I was cloning the recent release v1.2-rc-1 :)

**Comment by mandarsd** [comment]
In order to maintain the project dependencies in a cleaner way, we are moving them to the npm package.json. This also enables us to utilise the github release versioning properly. 
Pointing it directly to branch instead of release tag should not be wise. Could you please include the font files in upcoming releases?

**Comment by khawkins98** [comment]
I've just rolled RC2 (https://github.com/ebiwd/EBI-Icon-fonts/releases/tag/v1.2-rc-2) and have tagged it on the v1.2 compiled code branch.

**Comment by mandarsd** [comment]
Excellent! Thanks
Closing the issue.
