### ISSUE TITLE
Size difference with icon-functional or icon-generic

### ISSUE THREAD

**Issue by tschaka1904** [ebiwd/EBI-Icon-fonts#14]
I wanted to use buttons with icons and whilst implementing it, it seemed that either icon-functional or icon-generic are influencing the size of the button. 
![screen shot 2017-06-26 at 11 40 42](https://user-images.githubusercontent.com/5269116/27535918-9897ca58-5a64-11e7-900b-8f75334d0304.png)

You can see that the Basket button is bigger then the other.

**Comment by khawkins98** [comment]
Are you sure you're using only the `v1.1` css? 

In the older EBI Icon Fonts there was some manual adjusting of font sizes to compensate for the iconmoo process. That workaround was removed in `v1.2`.

I tried to recreate and here's what I got: 
![image](https://user-images.githubusercontent.com/928100/28259636-1eb081d2-6acf-11e7-9e3e-a396ffc867d9.png)
https://codepen.io/khawkins98/pen/awxaWq

The code structure:
```html

<div class="column medium-3 small-6 text-center">
  <a class="button medium-12 columns" href="#">
    <h3 class="icon icon-functional white-color" data-icon="="></h3> 
    <h5 class="white-color">Download</h5>
  </a>
</div>

```

The only other thing that might come to mind is if there's a `<p>` tag or such on the sample icon.
