### ISSUE TITLE
Replace link of React package

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Icon-fonts#16]
In the [main fonts page](http://www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.2/), could you change the link for React users so that it points at the NPM published package, https://www.npmjs.com/package/react-ebi-species,  instead of the GitHub repo?

**Comment by khawkins98** [comment]
Made the change, but it won't go live on the main EBI documentation page (www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.2/)  until I tag the next release. Probably sometime next week.
