### ISSUE TITLE
Generic-reviewed icon do not render properly

### ISSUE THREAD

**Issue by ftabaro** [ebiwd/EBI-Icon-fonts#18]
Please, check out the attached image. The reviewed icon from the generic set do not render properly.

![screenshot from 2017-09-20 10 10 08](https://user-images.githubusercontent.com/1375504/30633478-0dbef606-9dec-11e7-80a1-00e83f19641a.png)

**Comment by khawkins98** [comment]
Is this still happening for you? At one point I think the SVG source was invalid/corrupt, but this now seems to be fine.

If it is still broken for you, could you:
- Let me know the URL
- If it's happening on all browsers
- See if it also affects https://www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.1/#EBI-Generic

Apologies I'm just now seeing this!

**Comment by ftabaro** [comment]
We tested the current GitHub version, works fine. However, the package from NPM still points to 1.2.0-rc-2. For the time being we have built using the latest of your commits but, please, push the changes on NPM as well. Thanks.

**Comment by khawkins98** [comment]
Thanks for the note. Just pushed 1.2.3 (v1.2.4  doesn't have anything new, it's just a workaround for some issues we've had with the branch).
