### ISSUE TITLE
Can this be published in npm?

### ISSUE THREAD

**Issue by 4ndr01d3** [ebiwd/EBI-Icon-fonts#2]
Hey there is it possible to put this on npm, so we can manage the versioning of it.
Thanks.

**Comment by khawkins98** [comment]
I've done a basic publishing for npm. See: https://www.npmjs.com/package/EBI-Icon-fonts

But in general the current workflow for these files is, well, rather not good. It's a very manual process done by a print designer in Illustrator. The whole thing needs an overhaul, along with proper versioning.

**Comment by 4ndr01d3** [comment]
Thanks, wit this at least will be easier to incorporate it into our workflow.

**Comment by khawkins98** [comment]
Assigning to v1.2 for future review.
