### ISSUE TITLE
Icon code snippets with class are wrong

### ISSUE THREAD

**Issue by monicajianu** [ebiwd/EBI-Icon-fonts#24]
The examples on the [Style lab webpage](https://www.ebi.ac.uk/style-lab/general/fonts/v1.3/) say the usage is:
`<i class=".icon-ebi icon-address-book"></i>`
when it should be:
`<i class='icon icon-common icon-address-book'></i>`

Or at least that's what I've gathered from poking around in the CSS file.

**Comment by khawkins98** [comment]
Thanks for reporting. This has been corrected. https://www.ebi.ac.uk/style-lab/general/fonts/v1.3/
