### ISSUE TITLE
Icons in custom web components

### ISSUE THREAD

**Issue by Flowdihow** [ebiwd/EBI-Icon-fonts#26]
Hi,

I'd like to use the EBI icons in web components. However, I realized that the CSS selector has a html prefix to match the parent html tag. It seems that in a shadow root, the html is not seen, hence the respective CSS class is not applied. 

The problem is fixed by removing the html element selector i.e.:

```
html i.icon-chemistry,
html input.icon-chemistry,
html .icon-chemistry:before {
  font-family: 'EBI-Chemistry';
}

```
to 
```
i.icon-chemistry,
input.icon-chemistry,
 .icon-chemistry:before {
  font-family: 'EBI-Chemistry';
}
```

Any comments on this?

**Comment by khawkins98** [comment]
Thanks for the ticket on this. 

I expect this was a legacy issue from when the fonts were relying on modernizr. 

I've committed a change to the v1.3 dev branch, it should be available in a few minutes at https://dev.ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css

If that works as expected, I'll add it to the v1.3 beta (a final release should happen in the coming weeks).
