### ISSUE TITLE
Urgent! - Old font files not available

### ISSUE THREAD

**Issue by mandarsd** [ebiwd/EBI-Icon-fonts#30]
Font files served from -
https://www.ebi.ac.uk/web_guidelines/fonts/EBI-Generic/fonts/*
are not available.

All of the PDBe older applications are impacted.

**Comment by khawkins98** [comment]
Hi Mandar. Do you mean the Helvetica fonts?

If so, these were removed in February 2018 for various reasons. See: https://github.com/ebiwd/EBI-Icon-fonts/issues/8#issuecomment-357188416

(That was also done in collaboration with the WGC)

I'm surprised the change would be disruptive, or is it the error in the console that you're concerned about?

**Comment by mandarsd** [comment]
Hi Ken,
I've the idea about Helvatica fonts removal. These are some other ones -
![image](https://user-images.githubusercontent.com/12937838/67301740-c0284c80-f4e7-11e9-9c8e-c21771e27afc.png)

**Comment by khawkins98** [comment]
Ah, right. It looks like one of the old server URLs might not be working (ping @pwalter-ebi )

In the meantime -- and perhaps as a general improvement -- the CDN URL is more performance and reliable, here's for v1.1: https://ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.1/fonts.css

**Comment by khawkins98** [comment]
Oh and if you can give us one of the URLs impacted that'd be helpful for checking.

**Comment by khawkins98** [comment]
There was a server migration issue that @pwalter-ebi has now resolved. Should be working well again.

**Comment by mandarsd** [comment]
Yes it is. Thanks @khawkins98 and @pwalter-ebi
