### ISSUE TITLE
Old icon images missing

### ISSUE THREAD

**Issue by mandarsd** [ebiwd/EBI-Icon-fonts#31]
Similar to - https://github.com/ebiwd/EBI-Icon-fonts/issues/30

Example - https://www.ebi.ac.uk/web_guidelines/images/icons/EBI-Functional/Functional%20icons/expand.png

**Comment by khawkins98** [comment]
Was a similar issue to #30. @pwalter-ebi has resolved it. 

This has been a result of the migration away from the old deployment/VMs.

**Comment by mandarsd** [comment]
Thanks, working fine now
