### ISSUE TITLE
What's the deal with Garmond?

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Icon-fonts#5]
We load it by @font-face [in fonts.css line 1-7](https://github.com/ebiwd/EBI-Icon-fonts/blob/v1.1/fonts.css#L1-L7) and again with an [@import at line 22](https://github.com/ebiwd/EBI-Icon-fonts/blob/v1.1/fonts.css#L22)

On top of loading it twice, is it even used anywhere? Is this a bit of cruft from years past?

**Comment by peter-walter** [comment]
Not sure where this has come from as Garamond is not mentioned in http://wwwdev.ebi.ac.uk/web_guidelines/css/compliance/develop/ebi-visual.css

**Comment by khawkins98** [comment]
We've removed this in 1.2.
