### ISSUE TITLE
Map species icons to Ensembl species names as well as to their common names

### ISSUE THREAD

**Issue by wbazant** [ebiwd/EBI-Icon-fonts#9]
Okay this issue is just a shameless plug for
https://github.com/wbazant/react-ebi-species

To use icons programmatically we needed to curate the mapping of Ensembl species to the right icons. We use it on the differential results page among other places: http://www.ebi.ac.uk/gxa/genesets/GO:0008344#differential

**Comment by khawkins98** [comment]
That's great -- thanks for letting us know, plugged it in small print on the readme: f4bb3c93949d87eb46fbcb1125ad92ebdf41c62c

**Comment by wbazant** [comment]
@khawkins98 I feel honoured! 

TBH I only know of one instance of somebody else finding it useful - Gustavo told me he looked how the mapping was done for another component he was writing - but you never know, right?
